@echo off
setlocal enabledelayedexpansion

echo ====================================================
echo   VSBEC IT Task Manager - Android APK Build Tool
echo ====================================================
echo.

cd /d "%~dp0"

:: 1. Prioritize Android Studio's bundled JBR (Java 21/25) for Capacitor 7 compatibility
if exist "C:\Program Files\Android\Android Studio\jbr\bin\java.exe" (
    set "JAVA_HOME=C:\Program Files\Android\Android Studio\jbr"
    set "PATH=!JAVA_HOME!\bin;!PATH!"
    echo [*] Using Android Studio JBR (Java 21+ compatible):
    echo     !JAVA_HOME!
) else if exist "C:\Java\jdk21\bin\java.exe" (
    set "JAVA_HOME=C:\Java\jdk21"
    set "PATH=!JAVA_HOME!\bin;!PATH!"
    echo [*] Using JDK 21:
    echo     !JAVA_HOME!
)

:: 2. Check for Android SDK in standard paths if not set
if "%ANDROID_HOME%"=="" (
    if exist "%LOCALAPPDATA%\Android\Sdk\platforms" (
        set "ANDROID_HOME=%LOCALAPPDATA%\Android\Sdk"
        set "ANDROID_SDK_ROOT=%LOCALAPPDATA%\Android\Sdk"
    ) else if exist "C:\Android\Sdk\platforms" (
        set "ANDROID_HOME=C:\Android\Sdk"
        set "ANDROID_SDK_ROOT=C:\Android\Sdk"
    )
)

echo [*] Android SDK: %ANDROID_HOME%

:: Ensure web assets are built
if not exist "..\..\dist\index.html" (
    echo [*] Web build dist/ missing. Building React application...
    pushd ..\..
    call npm run build
    popd
)

:: 3. Automatically ensure android\local.properties is properly configured
if not exist "android" (
    echo [*] Initializing Capacitor Android platform...
    call npx cap add android
)

if not "%ANDROID_HOME%"=="" (
    set "FORMATTED_SDK=%ANDROID_HOME:\=\\%"
    > "android\local.properties" (
        echo ## Auto-generated by VSBEC build-apk.bat
        echo sdk.dir=!FORMATTED_SDK!
    )
)

echo.
echo [1/3] Syncing Web Assets & Injecting Mobile API Gateway...
call node inject-gateway.cjs

echo.
echo [2/3] Installing Capacitor Dependencies...
call npm install --no-audit

echo.
echo [3/3] Syncing Assets to Native Android Project...
call npx cap sync android

echo.
echo ====================================================
echo Compiling Android APK with Gradle...
echo ====================================================

if not "%ANDROID_HOME%"=="" (
    cd android
    call .\gradlew.bat assembleDebug
    if !ERRORLEVEL! equ 0 (
        echo.
        echo ====================================================
        echo [SUCCESS] Android APK compiled successfully!
        echo ====================================================
        cd ..
        if not exist "dist-apk" mkdir "dist-apk"
        copy /y "android\app\build\outputs\apk\debug\app-debug.apk" "dist-apk\VSBEC-IT-TaskManager.apk" >nul
        if not exist "..\..\dist-apk" mkdir "..\..\dist-apk"
        copy /y "android\app\build\outputs\apk\debug\app-debug.apk" "..\..\dist-apk\VSBEC-IT-TaskManager.apk" >nul
        echo.
        echo ----------------------------------------------------
        echo Ready-to-Install APK File:
        echo   standalone-packaging\android-apk\dist-apk\VSBEC-IT-TaskManager.apk
        echo   dist-apk\VSBEC-IT-TaskManager.apk
        echo ----------------------------------------------------
        echo.
        echo Transfer this APK to your Android phone via USB,
        echo WhatsApp, Google Drive, or local share, and tap Install!
        echo ====================================================
        pause
        exit /b 0
    ) else (
        echo.
        echo [!] Direct Gradle compile encountered an issue.
        cd ..
    )
)

echo.
echo Opening project in Android Studio...
call npx cap open android 2>nul
pause
